name: CI/CD Test-app

on:
  push:
    tags:
      - 'v*.*.*'
    branches: 'main'
    
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        
      - name: Get latest tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-latest-tag@v1


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:${{ steps.latest_tag.outputs.tag }}

      - name: new_name
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:${{ steps.latest_tag.outputs.tag }}

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' 
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV


      - name: Set Kubeconfig Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Version k8s
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.2'

      - name: Deploying
        run: kubectl set image -n ${{ secrets.NAME_SPACE }} deployment/web-test-app test-app=nikolaivasilyev/web.test.app:${{ env.RELEASE_VERSION }}
