name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest  
    steps:
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Cluster Authentication
        run: cat ${{ secrets.KUBECONFIG }} > /tmp/kubeconfig
      
      - name: Deploying
        run: kubectl --kubeconfig=/tmp/kubeconfig -n ${{ secrets.NAME_SPACE }} patch deployment web-test-app --patch "{"spec": {"template": {"spec": {"containers": [{"name": "test-app", "image": "${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}"}]}}}}"
